/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_patch_Launch */

#ifndef _Included_com_example_demo_patch_Launch
#define _Included_com_example_demo_patch_Launch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_patch_Launch
 * Method:    getNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_demo_patch_Launch_getNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
